language: objective-c
cache: cocoapods
osx_image: xcode8.1

before_install:
  - brew install swiftlint
  - pod install --repo-update
  - gem update fastlane --no-ri --no-rdoc --no-document

script: travis/script.sh
